<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Ming Chen &amp; Wenqiang Feng" />


<title>Homework #9</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">STAT 537: Statistics for Research I</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Notes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Chapter 1</li>
    <li>
      <a href="hw1.html">Note #1</a>
    </li>
    <li>
      <a href="hw2.html">Note #2</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Chapter 2</li>
    <li>
      <a href="hw1.html">Note #3</a>
    </li>
    <li>
      <a href="hw2.html">Note #4</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Homework
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Week 1</li>
    <li>
      <a href="hw1.html">HW #1</a>
    </li>
    <li>
      <a href="hw2.html">HW #2</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Week 2</li>
    <li>
      <a href="hw3.html">HW #3</a>
    </li>
    <li>
      <a href="hw4.html">HW #4</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Week 3</li>
    <li>
      <a href="hw5.html">HW #5</a>
    </li>
    <li>
      <a href="hw6.html">HW #6</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Week 4</li>
    <li>
      <a href="hw7.html">HW #7</a>
    </li>
    <li>
      <a href="hw8.html">HW #8</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Week 5</li>
    <li>
      <a href="hw9.html">HW #9</a>
    </li>
    <li>
      <a href="hw10.html">HW #10</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Week 6</li>
    <li>
      <a href="hw11.html">HW #11</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    Project
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Project 1</li>
    <li>
      <a href="project1.html">Project #1</a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Project 2</li>
    <li>
      <a href="project2.html">Project #2</a>
    </li>
  </ul>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    About
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/runawayhorse001/STAT537">
    <span class="fa fa-github"></span>
     
  </a>
</li>
<li>
  <a href="http://web.utk.edu/~wfeng1">
    <span class="fa fa-question fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Homework #9</h1>
<h4 class="author"><em>Ming Chen &amp; Wenqiang Feng</em></h4>
<h4 class="date"><em>2/2/2017</em></h4>

</div>


<div id="you-can-also-get-the-pdf-format-of-wenqiangs-homework." class="section level2">
<h2>You can also get the <a href="./pdf/HW9.pdf">PDF format</a> of Wenqiang’s Homework.</h2>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<pre class="r"><code>## response variable: PULSE
## predictor variables: RUN, SMOKE, HEIGHT, WEIGHT, PHYS1, PHYS2
mlrdata = read.table(&quot;./data/ex13-69.TXT&quot;, header = T, row.names = 1)
mlrdata$RUN = as.factor(mlrdata$RUN)
mlrdata$RUN = relevel(mlrdata$RUN, ref = &quot;0&quot;)
mlrdata$SMOKE = as.factor(mlrdata$SMOKE)
mlrdata$SMOKE = relevel(mlrdata$SMOKE, ref=&quot;0&quot;)
mlrdata$PHYS1 = as.factor(mlrdata$PHYS1)
mlrdata$PHYS1 = relevel(mlrdata$PHYS1, ref=&quot;0&quot;)
mlrdata$PHYS2 = as.factor(mlrdata$PHYS2)
mlrdata$PHYS2 = relevel(mlrdata$PHYS2, ref=&quot;0&quot;)</code></pre>
</div>
<div id="problem-a" class="section level2">
<h2>problem a</h2>
<pre class="r"><code>mlrfit = lm(PULSE~RUN+SMOKE+HEIGHT+WEIGHT+PHYS1+PHYS2, data=mlrdata)
summary(mlrfit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = PULSE ~ RUN + SMOKE + HEIGHT + WEIGHT + PHYS1 + 
##     PHYS2, data = mlrdata)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -10.135  -3.875  -1.205   4.951  13.520 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -26.36485   36.53646  -0.722 0.477810    
## RUN1         11.76733    2.67552   4.398 0.000209 ***
## SMOKE1       -7.02414    2.70636  -2.595 0.016175 *  
## HEIGHT       -0.02090    0.59180  -0.035 0.972128    
## WEIGHT        0.05721    0.08294   0.690 0.497239    
## PHYS11       13.55492    4.21419   3.216 0.003825 ** 
## PHYS21        7.89397    3.94366   2.002 0.057250 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.817 on 23 degrees of freedom
## Multiple R-squared:  0.6363, Adjusted R-squared:  0.5414 
## F-statistic: 6.706 on 6 and 23 DF,  p-value: 0.0003324</code></pre>
<pre class="r"><code>beta0 = coef(mlrfit)[&#39;(Intercept)&#39;]
betaRun1 = coef(mlrfit)[&#39;RUN1&#39;]
betaSmoke1 = coef(mlrfit)[&#39;SMOKE1&#39;]
betaHeight = coef(mlrfit)[&#39;HEIGHT&#39;]
betaWeight = coef(mlrfit)[&#39;WEIGHT&#39;]
betaPhys1 = coef(mlrfit)[&#39;PHYS11&#39;]
betaPhys2 = coef(mlrfit)[&#39;PHYS21&#39;]</code></pre>
<p>Full Model: PULSE = -26.3648455 + 11.7673345*(RUN=1) -7.0241413*(SMOKE=1) -0.0209031*(HEIGHT) + 0.0572127*(WEIGHT) + 13.5549219*(PHYS1) + 7.8939749*(PHYS2)</p>
</div>
<div id="problem-b" class="section level2">
<h2>problem b</h2>
<pre class="r"><code>rstudentVal = rstudent(mlrfit)
cooksDisVal = cooks.distance(mlrfit)
plot(rstudentVal~cooksDisVal, xlab=&quot;Cook&#39;s Distance&quot;, 
     ylab=&quot;Studentized Residuals&quot;, ylim=c(-3,3))
abline(h=c(-2,2), lty=&quot;dashed&quot;, lwd=2, col=&quot;blue&quot;)</code></pre>
<p><img src="hw9_files/figure-html/unnamed-chunk-3-1.png" width="480" /></p>
<pre class="r"><code>potentialInfObs = cooksDisVal[rstudentVal&gt;2 | rstudentVal&lt;(-2)]
potentialInfObs</code></pre>
<pre><code>##      13 
## 0.27569</code></pre>
<p>No influential observations exit. There is one observation that has large studentized residual. However, Cook’s D for this observation is 0.27569, which indicates small influence on the overall fit of the model.</p>
<div id="problem-c" class="section level4">
<h4>problem c</h4>
<pre class="r"><code>stepwiseFit = step(mlrfit, direction = &quot;both&quot;, test=&quot;F&quot;)</code></pre>
<pre><code>## Start:  AIC=121.19
## PULSE ~ RUN + SMOKE + HEIGHT + WEIGHT + PHYS1 + PHYS2
## 
##          Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
## - HEIGHT  1      0.06 1068.9 119.19  0.0012 0.9721283    
## - WEIGHT  1     22.11 1090.9 119.81  0.4758 0.4972393    
## &lt;none&gt;                1068.8 121.19                      
## - PHYS2   1    186.20 1255.0 124.01  4.0068 0.0572504 .  
## - SMOKE   1    313.03 1381.8 126.90  6.7362 0.0161748 *  
## - PHYS1   1    480.78 1549.6 130.34 10.3458 0.0038248 ** 
## - RUN     1    898.91 1967.7 137.50 19.3437 0.0002087 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=119.19
## PULSE ~ RUN + SMOKE + WEIGHT + PHYS1 + PHYS2
## 
##          Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
## - WEIGHT  1     31.69 1100.6 118.07  0.7117 0.4072253    
## &lt;none&gt;                1068.9 119.19                      
## + HEIGHT  1      0.06 1068.8 121.19  0.0012 0.9721283    
## - PHYS2   1    191.59 1260.5 122.14  4.3019 0.0489647 *  
## - SMOKE   1    312.99 1381.9 124.90  7.0278 0.0139885 *  
## - PHYS1   1    480.73 1549.6 128.34 10.7941 0.0031208 ** 
## - RUN     1    903.56 1972.4 135.57 20.2881 0.0001465 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Step:  AIC=118.07
## PULSE ~ RUN + SMOKE + PHYS1 + PHYS2
## 
##          Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
## &lt;none&gt;                1100.6 118.07                      
## + WEIGHT  1     31.69 1068.9 119.19  0.7117 0.4072253    
## + HEIGHT  1      9.64 1090.9 119.81  0.2121 0.6492453    
## - PHYS2   1    173.38 1274.0 120.46  3.9383 0.0582760 .  
## - SMOKE   1    307.96 1408.5 123.47  6.9955 0.0139189 *  
## - PHYS1   1    466.73 1567.3 126.68 10.6020 0.0032378 ** 
## - RUN     1    881.25 1981.8 133.72 20.0179 0.0001456 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Stepwise regression selection indicates that <em>RUN</em>, <em>SMOKE</em>, <em>PHYS1</em> and <em>PHYS2</em> are important variables to the model.</p>
</div>
<div id="problem-d" class="section level4">
<h4>problem d</h4>
<p>Choose the four important variables to re-fit the model.</p>
<pre class="r"><code>finalMod = lm(PULSE~RUN+SMOKE+PHYS1+PHYS2, data=mlrdata)
summary(finalMod)</code></pre>
<pre><code>## 
## Call:
## lm(formula = PULSE ~ RUN + SMOKE + PHYS1 + PHYS2, data = mlrdata)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.1862  -4.1927  -0.5269   4.6858  12.9764 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  -18.302      3.649  -5.016 3.58e-05 ***
## RUN1          11.132      2.488   4.474 0.000146 ***
## SMOKE1        -6.963      2.633  -2.645 0.013919 *  
## PHYS11        13.325      4.092   3.256 0.003238 ** 
## PHYS21         7.451      3.754   1.985 0.058276 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.635 on 25 degrees of freedom
## Multiple R-squared:  0.6255, Adjusted R-squared:  0.5656 
## F-statistic: 10.44 on 4 and 25 DF,  p-value: 4.109e-05</code></pre>
<pre class="r"><code>beta0 = coef(finalMod)[&#39;(Intercept)&#39;]
betaRun1 = coef(finalMod)[&#39;RUN1&#39;]
betaSmoke1 = coef(finalMod)[&#39;SMOKE1&#39;]
betaPhys1 = coef(finalMod)[&#39;PHYS11&#39;]
betaPhys2 = coef(finalMod)[&#39;PHYS21&#39;]</code></pre>
<p>The result shows that only variable <em>RUN</em>, <em>SMOKE</em>, <em>PHYS1</em> have significant effect on <em>PULSE</em>.</p>
<ul>
<li><p>Final Model: PULSE = -18.3015205 + 11.1321293*(RUN=1) -6.9630238*(SMOKE=1) + 13.3251481*(PHYS1)</p>
<ul>
<li>Given that other variables are consistent, the pulse of people who ran was 11.132 higher than people who didn’t run.</li>
<li>Given that other variables are consistent, the pulse of people who smoke was 6.963 lower than people who don’t smoke.</li>
<li>Given that other variables are consistent, the pulse of people who did a lot of physical exercise is 13.325 higher than people who didn’t.</li>
</ul></li>
</ul>
</div>
</div>

<center>Copyright &copy; 2017 Ming Chen  & Wenqiang Feng. All rights reserved.</center>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
